#!/usr/bin/env bash
#
# kino - run doppler inside a cage (kage) session, logging all output and
#        optionally pausing so gdb can attach to the whole process tree.

set -euo pipefail

readonly PROG=${0##*/}
readonly LOG="${HOME}/kino.log"
readonly RESOLUTION="640x480"
readonly GDB_SCRIPT="${XDG_CACHE_HOME:-$HOME/.cache}/kino/attach.gdb"

usage() {
	cat <<EOF
Usage: ${PROG} -m MODE [-g]
       ${PROG} -h

Runs doppler inside a cage session:

	cage -r ${RESOLUTION} -f FIT -F FILTER -- doppler

All output (stdout and stderr) of cage, doppler and every process spawned
within the session is written to the following file, truncated on each run:

	${LOG}

Options:
	-m MODE   Scaling mode (required). One of:
	            1:1           -f exact -F nearest
	            fit-nearest   -f fit -F nearest
	            fit-bilinear  -f fit -F bilinear
	-g        Debug mode: pause before starting cage and wait for gdb to
	          attach. cage, doppler and every descendant process are then
	          under gdb control.
	-h        Show this help and exit.

Debugging (-g):
	1. Start the session. The script prints its PID and waits:

	     ${PROG} -m fit-nearest -g

	2. In another shell, attach gdb using the generated command file:

	     gdb -x ${GDB_SCRIPT}

	   If kernel.yama.ptrace_scope is 1 or higher, prefix with sudo.

	3. At the (gdb) prompt the session has not started yet. Prepare it:

	     break FUNCTION or FILE:LINE    breakpoints (pending until loaded)
	     catch exec                     stop whenever a process execs
	     directory ~/src/doppler        extra source search paths
	     set debug-file-directory DIR   where to find split debug info

	   then type 'continue'. The launcher execs cage, and gdb follows cage
	   into doppler and every other child (Xwayland, helpers, ...).

	4. Useful commands once running:

	     Ctrl-C                  interrupt the whole session
	     info inferiors          list the processes gdb controls
	     inferior N              switch to process N (then bt, frame, ...)
	     add-symbol-file F ADDR  load extra symbols by hand
	     set \$kino_resume = 0    stop (don't auto-continue) when a child exits

	5. Program output continues to go to ${LOG}:

	     tail -f ${LOG}

	Note: when gdb stops, the compositor freezes with it, including VT
	switching. Run gdb over SSH or from another machine's terminal, or run
	${PROG} nested inside an existing Wayland/X11 session.
EOF
}

die() {
	printf '%s: %s\n' "$PROG" "$*" >&2
	printf "Try '%s -h' for help.\n" "$PROG" >&2
	exit 2
}

need() {
	command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

# Writes the gdb command file used to attach to process $1.
write_gdb_script() {
	local pid=$1
	mkdir -p "${GDB_SCRIPT%/*}"
	cat >"$GDB_SCRIPT" <<EOF
# Generated by ${PROG} for PID ${pid}. Overwritten on every '${PROG} -g' run.
set pagination off
set breakpoint pending on
# Keep every forked process under gdb control.
set detach-on-fork off
set follow-fork-mode parent
set follow-exec-mode same
# 'continue' and Ctrl-C act on all processes, not only the current one.
set schedule-multiple on

attach ${pid}

# In all-stop mode, gdb halts the whole session whenever any child exits.
# Resume automatically instead (disable with: set \$kino_resume = 0).
# This block is last so that a gdb built without Python still attaches.
set \$kino_resume = 1
python
import gdb

def _kino_resume():
	live = [i for i in gdb.inferiors() if i.pid > 0 and i.threads()]
	if not live:
		return
	try:
		if gdb.selected_inferior().pid == 0:
			live[0].threads()[0].switch()
		thread = gdb.selected_thread()
		if thread is not None and thread.is_running():
			return
		gdb.execute("continue")
	except gdb.error as err:
		print("kino: auto-resume failed: %s" % err)

def _kino_on_exit(event):
	if gdb.convenience_variable("kino_resume") in (None, 0):
		return
	gdb.post_event(_kino_resume)

gdb.events.exited.connect(_kino_on_exit)
end

echo \\n${PROG}: attached. Set breakpoints etc., then 'continue' to start cage.\\n
EOF
}

# Blocks until a debugger is ptrace-attached to this shell. Builtins only,
# so no stray child processes are created while gdb is attached.
wait_for_tracer() {
	local key value fd
	exec {fd}<> <(:)
	while :; do
		while read -r key value; do
			if [[ $key == TracerPid: ]]; then
				[[ $value != 0 ]] && break 2
				break
			fi
		done </proc/$$/status
		read -r -t 0.2 -u "$fd" || true
	done
	exec {fd}<&-
}

gdb_prefix() {
	local scope=0 yama=/proc/sys/kernel/yama/ptrace_scope
	[[ -r $yama ]] && scope=$(<"$yama")
	case $scope in
		0) ;;
		1|2) (( EUID == 0 )) || printf 'sudo ' ;;
		*) die "kernel.yama.ptrace_scope is $scope; attaching is disabled until reboot" ;;
	esac
}

main() {
	if (( $# == 0 )); then
		usage
		exit 0
	fi

	local mode="" debug=0 opt
	while getopts ":m:gh" opt; do
		case $opt in
			m) mode=$OPTARG ;;
			g) debug=1 ;;
			h) usage; exit 0 ;;
			:) die "option -$OPTARG requires an argument" ;;
			\?) die "unknown option: -$OPTARG" ;;
		esac
	done
	shift $(( OPTIND - 1 ))
	(( $# == 0 )) || die "unexpected argument: $1"

	local fit filter
	case $mode in
		1:1) fit=exact; filter=nearest ;;
		fit-nearest) fit=fit; filter=nearest ;;
		fit-bilinear) fit=fit; filter=bilinear ;;
		"") die "option -m is required" ;;
		*) die "invalid mode '$mode' (expected 1:1, fit-nearest or fit-bilinear)" ;;
	esac

	need kage
	need doppler

	local -a cmd=(kage -r "$RESOLUTION" -f "$fit" -F "$filter" -- doppler)

	: >"$LOG" 2>/dev/null || die "cannot write to $LOG"

	if (( debug )); then
		local prefix
		prefix=$(gdb_prefix)
		write_gdb_script "$$"
		printf '%s: PID %s, waiting for gdb. Attach from another shell with:\n\n' "$PROG" "$$" >&2
		printf '\t%sgdb -x %s\n\n' "$prefix" "$GDB_SCRIPT" >&2
		printf '%s: output is logged to %s\n' "$PROG" "$LOG" >&2
		wait_for_tracer
		printf '%s: debugger attached, starting cage\n' "$PROG" >&2
	fi

	# From here on, cage and every descendant inherit these descriptors.
	exec >>"$LOG" 2>&1
	printf '=== %(%F %T)T: %s\n' -1 "${cmd[*]}"
	exec "${cmd[@]}"
}

main "$@"
